version: "3.5"
services: 
  web:
    image: nginx
    volumes:
    - ./web/public:/usr/share/nginx/html:ro
    - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
  api:
    image: api
    command: ./bin/app
    build:
      context: api
    ports:
      - 4000:4000
  db:
    image: ibmcom/db2
    privileged: true
    environment:
    - LICENSE=accept
    - DB2INSTANCE=db2inst1
    - DB2INST1_PASSWORD=password
    - DBNAME=sample
    - SAMPLEDB=true
    ports:
    - 50000:50000